# coding: utf-8

"""
    Gotyai API v3

    Gotyai API : the Spartan explainable AI   # noqa: E501

    OpenAPI spec version: 3.0.2
    Contact: contact@namsor.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import gotyai_client
from gotyai_client.models.batch_fit_in import BatchFitIn  # noqa: E501
from gotyai_client.rest import ApiException


class TestBatchFitIn(unittest.TestCase):
    """BatchFitIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBatchFitIn(self):
        """Test BatchFitIn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gotyai_client.models.batch_fit_in.BatchFitIn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
