# coding: utf-8

"""
    Gotyai API v3

    Gotyai API : the Spartan explainable AI   # noqa: E501

    OpenAPI spec version: 3.0.2
    Contact: contact@namsor.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import gotyai_client
from gotyai_client.models.spam_event_out import SpamEventOut  # noqa: E501
from gotyai_client.rest import ApiException


class TestSpamEventOut(unittest.TestCase):
    """SpamEventOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpamEventOut(self):
        """Test SpamEventOut"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gotyai_client.models.spam_event_out.SpamEventOut()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
