# coding: utf-8

"""
    Gotyai API v3

    Gotyai API : the Spartan explainable AI   # noqa: E501

    OpenAPI spec version: 3.0.2
    Contact: contact@namsor.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import gotyai_client
from gotyai_client.api.classify_api import ClassifyApi  # noqa: E501
from gotyai_client.rest import ApiException


class TestClassifyApi(unittest.TestCase):
    """ClassifyApi unit test stubs"""

    def setUp(self):
        self.api = gotyai_client.api.classify_api.ClassifyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_explain_many(self):
        """Test case for explain_many

        Predict a category given the subjet's features, with explainability.  # noqa: E501
        """
        pass

    def test_explain_one(self):
        """Test case for explain_one

        Predict a category given the subjet's features, with explainability.  # noqa: E501
        """
        pass

    def test_fit_many(self):
        """Test case for fit_many

        Fit multiple rows in the training sample (up to 100)  # noqa: E501
        """
        pass

    def test_fit_one(self):
        """Test case for fit_one

        Fit one row in the training sample.  # noqa: E501
        """
        pass

    def test_multinomial(self):
        """Test case for multinomial

        Get the multinomila classifier by its name.  # noqa: E501
        """
        pass

    def test_multinomial1(self):
        """Test case for multinomial1

        Get all the multinomila classifiers.  # noqa: E501
        """
        pass

    def test_multinomial_create(self):
        """Test case for multinomial_create

        Create a multinomial classiifer  # noqa: E501
        """
        pass

    def test_predict_many(self):
        """Test case for predict_many

        Predict a category given the subjecct's features, for up to 100 rows at a time.  # noqa: E501
        """
        pass

    def test_predict_one(self):
        """Test case for predict_one

        Predict a category given the subjet's features  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
