# coding: utf-8

"""
    Gotyai API v3

    Gotyai API : the Spartan explainable AI   # noqa: E501

    OpenAPI spec version: 3.0.2
    Contact: contact@namsor.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import gotyai_client
from gotyai_client.models.api_plans_out import APIPlansOut  # noqa: E501
from gotyai_client.rest import ApiException


class TestAPIPlansOut(unittest.TestCase):
    """APIPlansOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAPIPlansOut(self):
        """Test APIPlansOut"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gotyai_client.models.api_plans_out.APIPlansOut()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
