# coding: utf-8

"""
    Gotyai API v3

    Gotyai API : the Spartan explainable AI   # noqa: E501

    OpenAPI spec version: 3.0.2
    Contact: contact@namsor.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import gotyai_client
from gotyai_client.models.billing_info_in_out import BillingInfoInOut  # noqa: E501
from gotyai_client.rest import ApiException


class TestBillingInfoInOut(unittest.TestCase):
    """BillingInfoInOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBillingInfoInOut(self):
        """Test BillingInfoInOut"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gotyai_client.models.billing_info_in_out.BillingInfoInOut()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
