# coding: utf-8

"""
    Gotyai API v3

    Gotyai API : the Spartan explainable AI   # noqa: E501

    OpenAPI spec version: 3.0.2
    Contact: contact@namsor.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class APIUsageHistoryOut(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'detailed_usage': 'list[APICounterV2Out]'
    }

    attribute_map = {
        'detailed_usage': 'detailedUsage'
    }

    def __init__(self, detailed_usage=None):  # noqa: E501
        """APIUsageHistoryOut - a model defined in OpenAPI"""  # noqa: E501

        self._detailed_usage = None
        self.discriminator = None

        if detailed_usage is not None:
            self.detailed_usage = detailed_usage

    @property
    def detailed_usage(self):
        """Gets the detailed_usage of this APIUsageHistoryOut.  # noqa: E501

        Detailed usage as reported by the deduplicating API counter.  # noqa: E501

        :return: The detailed_usage of this APIUsageHistoryOut.  # noqa: E501
        :rtype: list[APICounterV2Out]
        """
        return self._detailed_usage

    @detailed_usage.setter
    def detailed_usage(self, detailed_usage):
        """Sets the detailed_usage of this APIUsageHistoryOut.

        Detailed usage as reported by the deduplicating API counter.  # noqa: E501

        :param detailed_usage: The detailed_usage of this APIUsageHistoryOut.  # noqa: E501
        :type: list[APICounterV2Out]
        """

        self._detailed_usage = detailed_usage

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, APIUsageHistoryOut):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
