# coding: utf-8

"""
    Gotyai API v3

    Gotyai API : the Spartan explainable AI   # noqa: E501

    OpenAPI spec version: 3.0.2
    Contact: contact@namsor.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class CacheMetricsOut(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'cache_name': 'str',
        'cache_stats': 'str'
    }

    attribute_map = {
        'cache_name': 'cacheName',
        'cache_stats': 'cacheStats'
    }

    def __init__(self, cache_name=None, cache_stats=None):  # noqa: E501
        """CacheMetricsOut - a model defined in OpenAPI"""  # noqa: E501

        self._cache_name = None
        self._cache_stats = None
        self.discriminator = None

        if cache_name is not None:
            self.cache_name = cache_name
        if cache_stats is not None:
            self.cache_stats = cache_stats

    @property
    def cache_name(self):
        """Gets the cache_name of this CacheMetricsOut.  # noqa: E501

        Internal cache name  # noqa: E501

        :return: The cache_name of this CacheMetricsOut.  # noqa: E501
        :rtype: str
        """
        return self._cache_name

    @cache_name.setter
    def cache_name(self, cache_name):
        """Sets the cache_name of this CacheMetricsOut.

        Internal cache name  # noqa: E501

        :param cache_name: The cache_name of this CacheMetricsOut.  # noqa: E501
        :type: str
        """

        self._cache_name = cache_name

    @property
    def cache_stats(self):
        """Gets the cache_stats of this CacheMetricsOut.  # noqa: E501

        Internal cache metrics (hit rade etc.)  # noqa: E501

        :return: The cache_stats of this CacheMetricsOut.  # noqa: E501
        :rtype: str
        """
        return self._cache_stats

    @cache_stats.setter
    def cache_stats(self, cache_stats):
        """Sets the cache_stats of this CacheMetricsOut.

        Internal cache metrics (hit rade etc.)  # noqa: E501

        :param cache_stats: The cache_stats of this CacheMetricsOut.  # noqa: E501
        :type: str
        """

        self._cache_stats = cache_stats

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CacheMetricsOut):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
