# coding: utf-8

"""
    Gotyai API v3

    Gotyai API : the Spartan explainable AI   # noqa: E501

    OpenAPI spec version: 3.0.2
    Contact: contact@namsor.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ClassifierSpecIn(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'categories': 'list[str]',
        'classifier_name': 'str'
    }

    attribute_map = {
        'categories': 'categories',
        'classifier_name': 'classifierName'
    }

    def __init__(self, categories=None, classifier_name=None):  # noqa: E501
        """ClassifierSpecIn - a model defined in OpenAPI"""  # noqa: E501

        self._categories = None
        self._classifier_name = None
        self.discriminator = None

        if categories is not None:
            self.categories = categories
        if classifier_name is not None:
            self.classifier_name = classifier_name

    @property
    def categories(self):
        """Gets the categories of this ClassifierSpecIn.  # noqa: E501


        :return: The categories of this ClassifierSpecIn.  # noqa: E501
        :rtype: list[str]
        """
        return self._categories

    @categories.setter
    def categories(self, categories):
        """Sets the categories of this ClassifierSpecIn.


        :param categories: The categories of this ClassifierSpecIn.  # noqa: E501
        :type: list[str]
        """

        self._categories = categories

    @property
    def classifier_name(self):
        """Gets the classifier_name of this ClassifierSpecIn.  # noqa: E501


        :return: The classifier_name of this ClassifierSpecIn.  # noqa: E501
        :rtype: str
        """
        return self._classifier_name

    @classifier_name.setter
    def classifier_name(self, classifier_name):
        """Sets the classifier_name of this ClassifierSpecIn.


        :param classifier_name: The classifier_name of this ClassifierSpecIn.  # noqa: E501
        :type: str
        """

        self._classifier_name = classifier_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClassifierSpecIn):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
